; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34810.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
EXTRN	printf:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+80
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG7533	DB	'a=%d,b=%d,c=%d,d=%d,e=%d,f=%d,g=%d,h=%d', 0aH, 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	0a204H
xdata	ENDS
; Function compile flags: /Odtp
; File F:\Users\26644\study-assembly\08-printf\main.c
_TEXT	SEGMENT
main	PROC

; 1    : int main(){

$LN3:
	sub	rsp, 88					; 00000058H

; 2    :     printf("a=%d,b=%d,c=%d,d=%d,e=%d,f=%d,g=%d,h=%d\n",1,2,3,4,5,6,7,8);

	mov	DWORD PTR [rsp+64], 8
	mov	DWORD PTR [rsp+56], 7
	mov	DWORD PTR [rsp+48], 6
	mov	DWORD PTR [rsp+40], 5
	mov	DWORD PTR [rsp+32], 4
	mov	r9d, 3
	mov	r8d, 2
	mov	edx, 1
	lea	rcx, OFFSET FLAT:$SG7533
	call	printf

; 3    :     return 0;

	xor	eax, eax

; 4    : }

	add	rsp, 88					; 00000058H
	ret	0
main	ENDP
_TEXT	ENDS
END
