; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34810.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	f1
PUBLIC	f2
PUBLIC	main
EXTRN	printf:PROC
pdata	SEGMENT
$pdata$f1 DD	imagerel $LN3
	DD	imagerel $LN3+32
	DD	imagerel $unwind$f1
$pdata$f2 DD	imagerel $LN3
	DD	imagerel $LN3+36
	DD	imagerel $unwind$f2
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+22
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG7541	DB	'a=%d b=%d c=%d', 0aH, 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$f1 DD	010401H
	DD	02204H
$unwind$f2 DD	010401H
	DD	06204H
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File F:\Users\26644\study-assembly\07-stack\main.c
; Line 8
$LN3:
	sub	rsp, 40					; 00000028H
; Line 9
	call	f1
; Line 10
	call	f2
	npad	1
; Line 11
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
c$ = 32
b$ = 36
a$ = 40
f2	PROC
; File F:\Users\26644\study-assembly\07-stack\main.c
; Line 4
$LN3:
	sub	rsp, 56					; 00000038H
; Line 6
	mov	r9d, DWORD PTR c$[rsp]
	mov	r8d, DWORD PTR b$[rsp]
	mov	edx, DWORD PTR a$[rsp]
	lea	rcx, OFFSET FLAT:$SG7541
	call	printf
	npad	1
; Line 7
	add	rsp, 56					; 00000038H
	ret	0
f2	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 0
b$ = 4
c$ = 8
f1	PROC
; File F:\Users\26644\study-assembly\07-stack\main.c
; Line 1
$LN3:
	sub	rsp, 24
; Line 2
	mov	DWORD PTR a$[rsp], 1
	mov	DWORD PTR b$[rsp], 2
	mov	DWORD PTR c$[rsp], 3
; Line 3
	add	rsp, 24
	ret	0
f1	ENDP
_TEXT	ENDS
END
