; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34810.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	f1
PUBLIC	f2
PUBLIC	main
PUBLIC	??_C@_0BA@BILLKFBN@a?$DN?$CFd?5b?$DN?$CFd?5c?$DN?$CFd?6@ ; `string'
EXTRN	printf:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN6
	DD	imagerel $LN6+37
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT ??_C@_0BA@BILLKFBN@a?$DN?$CFd?5b?$DN?$CFd?5c?$DN?$CFd?6@
CONST	SEGMENT
??_C@_0BA@BILLKFBN@a?$DN?$CFd?5b?$DN?$CFd?5c?$DN?$CFd?6@ DB 'a=%d b=%d c='
	DB	'%d', 0aH, 00H				; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
c$1 = 48
b$2 = 48
a$3 = 48
main	PROC						; COMDAT
; File F:\Users\26644\study-assembly\07-stack\main.c
; Line 8
$LN6:
	sub	rsp, 40					; 00000028H
; Line 6
	mov	r9d, DWORD PTR c$1[rsp]
	lea	rcx, OFFSET FLAT:??_C@_0BA@BILLKFBN@a?$DN?$CFd?5b?$DN?$CFd?5c?$DN?$CFd?6@
	mov	r8d, DWORD PTR b$2[rsp]
	mov	edx, DWORD PTR a$3[rsp]
	call	printf
; Line 11
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT f2
_TEXT	SEGMENT
c$ = 8
b$ = 8
a$ = 8
f2	PROC						; COMDAT
; File F:\Users\26644\study-assembly\07-stack\main.c
; Line 6
	mov	r9d, DWORD PTR c$[rsp]
	lea	rcx, OFFSET FLAT:??_C@_0BA@BILLKFBN@a?$DN?$CFd?5b?$DN?$CFd?5c?$DN?$CFd?6@
	mov	r8d, DWORD PTR b$[rsp]
	mov	edx, DWORD PTR a$[rsp]
	jmp	printf
f2	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT f1
_TEXT	SEGMENT
f1	PROC						; COMDAT
; File F:\Users\26644\study-assembly\07-stack\main.c
; Line 3
	ret	0
f1	ENDP
_TEXT	ENDS
END
