; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34810.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
EXTRN	printf:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+23
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG7533	DB	'%d,%d,%d', 0aH, 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File F:\Users\26644\study-assembly\07-stack\practice\main.c
; Line 1
$LN3:
	sub	rsp, 40					; 00000028H
; Line 2
	lea	rcx, OFFSET FLAT:$SG7533
	call	printf
; Line 3
	xor	eax, eax
; Line 4
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
